# syntax=docker/dockerfile:1

# --- Stage 1: builder ---
# Installs Python dependencies in a normal, reliable environment. AWS
# Lambda's base image toolchain has caused repeated build failures
# (missing/incompatible C compiler for numpy's source build) — sidestep
# that entirely by never compiling anything inside the Lambda image at all.
# manylinux wheels installed here are ABI-compatible with the Lambda image
# at runtime regardless of which distro built them, as long as the wheel's
# declared minimum glibc is satisfied (it is, in both directions here).
FROM python:3.12-slim AS builder

WORKDIR /build
COPY app/requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --retries 5 --timeout 120 --index-url https://download.pytorch.org/whl/cpu --target=/deps torch

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --retries 5 --timeout 120 --target=/deps -r requirements.txt

# Pre-download the embedding model weights at BUILD time rather than on the
# first live request — without this, the first chat request after a cold
# start has to reach out to Hugging Face and download ~80MB before it can
# even embed the question, which is slow and (worse, for a real Lambda
# deploy) makes boot depend on an external network call succeeding.
ENV SENTENCE_TRANSFORMERS_HOME=/model_cache
RUN PYTHONPATH=/deps python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

# --- Stage 2: final Lambda runtime image ---
FROM public.ecr.aws/lambda/python:3.12

# Installed packages from the builder stage, placed directly on the task
# root (Lambda automatically adds LAMBDA_TASK_ROOT to sys.path).
COPY --from=builder /deps ${LAMBDA_TASK_ROOT}

# Pre-downloaded model weights — same env var so sentence-transformers finds
# them at the same path instead of trying to fetch them again.
ENV SENTENCE_TRANSFORMERS_HOME=/model_cache
COPY --from=builder /model_cache /model_cache
# Belt-and-suspenders: refuse to silently fall back to a network call if the
# cache is ever missing/misconfigured — fail loudly instead of hanging.
ENV HF_HUB_OFFLINE=1

# App code + the pre-built FAISS index (generated by ingest.py, committed to repo)
COPY app/ ${LAMBDA_TASK_ROOT}/

# Lambda container entrypoint: module.handler
CMD ["main.handler"]
